services:
  - type: web
    name: fadex-bot
    runtime: image
    repo: https://github.com/sashazhilin777-commits/Fadex
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: "8650869989:AAGQnalF4fm8zACYNFZPfKzcpPIOWhonqe8"
      - key: ADMIN_ID
        value: "937887465"
      - key: ADMIN_USERNAME
        value: "@Askeer_05"
      - key: ADMIN_PASSWORD
        value: "123"
      - key: USDT_WALLET
        value: "TJGaX62395xATZus3VEK2nWWaY6RNFh59X"
      - key: TON_API_KEY
        value: ""
